@"D:\7th Semester\CSE 302\Lab\Lab 3\banking.sql"

SELECT * FROM BRANCH;
SELECT * FROM CUSTOMER;
SELECT * FROM ACCOUNT;
SELECT * FROM LOAN;
SELECT * FROM DEPOSITOR;
SELECT * FROM BORROWER;

--01
SELECT BRANCH_NAME,BRANCH_CITY,ASSETS
FROM BRANCH 
WHERE ASSETS>1000000;

--02
SELECT ACCOUNT_NUMBER,BALANCE
FROM ACCOUNT 
WHERE BRANCH_NAME='Downtown' 
OR BALANCE BETWEEN 600 AND 750;

--03
SELECT ACCOUNT.ACCOUNT_NUMBER
FROM BRANCH JOIN ACCOUNT 
ON BRANCH.BRANCH_NAME=ACCOUNT.BRANCH_NAME
WHERE BRANCH.BRANCH_CITY='Rye';

--04
SELECT LOAN.LOAN_NUMBER
FROM LOAN JOIN BORROWER 
ON LOAN.LOAN_NUMBER=BORROWER.LOAN_NUMBER
JOIN CUSTOMER
ON BORROWER.CUSTOMER_NAME=CUSTOMER.CUSTOMER_NAME
WHERE LOAN.AMOUNT>=1000 AND CUSTOMER.CUSTOMER_CITY='Harrison';

--05
SELECT * 
FROM ACCOUNT
ORDER BY BALANCE DESC;

--06
SELECT * 
FROM CUSTOMER
ORDER BY CUSTOMER_CITY;

--07
SELECT CUSTOMER_NAME
FROM DEPOSITOR
INTERSECT
SELECT CUSTOMER_NAME
FROM BORROWER;

--08
SELECT C.CUSTOMER_NAME,C.CUSTOMER_STREET,C.CUSTOMER_CITY
FROM CUSTOMER C JOIN DEPOSITOR D
ON C.CUSTOMER_NAME=D.CUSTOMER_NAME
UNION
SELECT C.CUSTOMER_NAME,C.CUSTOMER_STREET,C.CUSTOMER_CITY
FROM CUSTOMER C JOIN BORROWER B
ON C.CUSTOMER_NAME=B.CUSTOMER_NAME;

--09
SELECT C.CUSTOMER_NAME, C.CUSTOMER_CITY
FROM CUSTOMER C JOIN BORROWER B 
ON C.CUSTOMER_NAME = B.CUSTOMER_NAME
MINUS
SELECT C.CUSTOMER_NAME, C.CUSTOMER_CITY
FROM CUSTOMER C JOIN DEPOSITOR D 
ON D.CUSTOMER_NAME = C.CUSTOMER_NAME;

--10
SELECT SUM(ASSETS) AS TOTAL_ASSETS
FROM BRANCH;

--11
SELECT BRANCH_NAME,AVG(BALANCE)
FROM ACCOUNT
GROUP BY BRANCH_NAME;

--12
SELECT B.BRANCH_CITY,AVG(A.BALANCE) AS AVG_BALANCE
FROM BRANCH B JOIN ACCOUNT A
ON B.BRANCH_NAME=A.BRANCH_NAME
GROUP BY B.BRANCH_CITY;

--13
SELECT BRANCH_NAME, MIN(AMOUNT) AS LOWEST_AMOUNT 
FROM LOAN
GROUP BY BRANCH_NAME;

--14
SELECT BRANCH_NAME,COUNT(AMOUNT) AS NUM_OF_LOAN
FROM LOAN
GROUP BY BRANCH_NAME;

--15
SELECT D.CUSTOMER_NAME,A.ACCOUNT_NUMBER,A.BALANCE AS MAX_BALANCE
FROM DEPOSITOR D JOIN ACCOUNT A
ON D.ACCOUNT_NUMBER=A.ACCOUNT_NUMBER
WHERE BALANCE=(SELECT MAX(BALANCE) FROM ACCOUNT);
